vaadin.productionMode: true

spring:
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:${DB_PORT:6543}/postgres?prepareThreshold=0
    username: ${DB_USER:postgres.rsuhstqfoaoabfzgezxr}
    password: ${DB_PASSWORD}