vaadin.productionMode: true

spring:
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.rsuhstqfoaoabfzgezxr
    password: ${DB_PASSWORD}
