server.port: ${PORT:8083}

spring:
  application.name: api-stress-test
  profiles.active: ${PROFILE:prod}
  config.import: optional:file:.env[.properties] # enable scanning of .env file

# Google OAuth
oath.url: /oauth2/authorization/google
spring.security.oauth2.client.registration.google:
  client-id: ${OAUTH_CLIENT_ID}
  client-secret: ${OAUTH_CLIENT_SECRET}

# Security
security.whitelist.ant-patterns: /icons/**,/images/**,/h2-console/**